chore: use third job to be required check

diff --git a/.github/workflows/layer.yml b/.github/workflows/layer.yml
--- a/.github/workflows/layer.yml
+++ b/.github/workflows/layer.yml
@@ -27,7 +27,7 @@ jobs:
             - "flow-examples/**"
             - ".github/workflows/layer.yml"
 
-  check:
+  layer-test:
     strategy:
       matrix:
         os: [ubuntu-latest, ubuntu-24.04-arm]
@@ -86,3 +86,19 @@ jobs:
           path: ~/.oocana/sessions
           retention-days: 1
         if: failure()
+
+  check:
+    runs-on: ubuntu-latest
+    needs: [layer-check]
+    if: ${{ always() }}
+    steps:
+      - name: check
+        run: |
+          exit_on_result() {
+            if [[ "$2" == "failure" || "$2" == "cancelled" ]]; then
+              echo "Job '$1' failed or was cancelled."
+              exit 1
+            fi
+          }
+
+          exit_on_result "layer-check" "${{ needs.layer-check.result }}"
